apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sam-service-triton 

resources:
- deployment.yaml 
- pvc.yaml
- service.yaml
- gateway.yaml 
- triton-server-rb.yaml
- triton-server-sa.yaml
- sam-service-triton-cert.yaml 

