apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triton-server-anyuid
  namespace: sam-service-triton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: triton-server
  namespace: sam-service-dev
